### ISSUE TITLE
speed test shows...

### ISSUE THREAD

**Issue by llombard** [Koheron/laser-development-kit#50]
... that the acquisition speed is 240Hz for 32k samples at 125MS/s.

so that's 7.7MS/s over the 125MS/s or 6% of the generated data that are transmitted. Not bad but may be improved by accumulating several 32k samples into an array and transferring this array in one connection. What do you think about this?

PS I reached 30% using a code found on RP forum, so it is possible :)

**Comment by jeanminet** [comment]
I measured similar speeds (a little above 250 Hz):

![figure_1](https://cloud.githubusercontent.com/assets/1735094/13503226/9518e418-e16e-11e5-84cb-bf36c72891b6.png)

Note that only 16k samples (8k for each adc) are transmitted so that corresponds to only 4MSps :snail:
However, each sample is stored on 32 bits (instead of 16 bits in the Red Pitaya design) because averaging is performed on the FPGA. 

In the present design, data is read from the Block RAM using a Master GP port in AXI-lite (no burst) configuration clocked at 200 MHz. I measured that 1 read operation (32 bits) takes 80 ns (16 clock cycles). So that's already 16384 x 80 ns = 1.3 ms to transfer the 16k samples from FPGA to CPU...

It is possible to reach much higher speeds using the High Performance port of the Zynq in a DMA configuration. I guess the code you found on Red Pitaya forum uses such a configuration (do you have a link ?)
Concerning your 30% value, I guess you were only transmitting one channel (30% x 125 MS/s x 2 channels x 16 bits/S = 1200 Mbps).

**Comment by llombard** [comment]
see thread http://forum.redpitaya.com/viewtopic.php?f=7&t=317&p=4494#p4494

with command rp_remote_acquire -m 1 -a 125.40.1.188 -p 9930 -u

Laurent

**Comment by llombard** [comment]
http://forum.redpitaya.com/viewtopic.php?f=7&t=317&p=4520#p4520

see my post updated today. I measured for a single channel 24% = 59.7MB/s / 250MS/s.

**Comment by jeanminet** [comment]
Speed has improved a little (release : https://github.com/Koheron/zynq-sdk/releases/tag/v0.6-beta.1)

![figure_1-3](https://cloud.githubusercontent.com/assets/1735094/15354504/49ad8e82-1cee-11e6-95ea-cbb6318fac66.png)

**Comment by jeanminet** [comment]
![figure_1-5](https://cloud.githubusercontent.com/assets/1735094/15552344/3e451f8e-22ba-11e6-9ee6-0f308451847c.png)
